// <auto-generated />
using System;
using GrailJobApi.Modules.CandidateProfile.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GrailJobApi.Modules.CandidateProfile.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CandidateProfileDbContext))]
    [Migration("20260407153446_ExtendAiProfileInsight")]
    partial class ExtendAiProfileInsight
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("candidate_profile")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GrailJobApi.Modules.CandidateProfile.Domain.CandidateProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ExtractedText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ImportedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<long>("SizeInBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("CandidateProfiles", "candidate_profile");
                });

            modelBuilder.Entity("GrailJobApi.Modules.CandidateProfile.Domain.CandidateProfile", b =>
                {
                    b.OwnsOne("GrailJobApi.Modules.CandidateProfile.Domain.AiProfileInsight", "AiProfileInsight", b1 =>
                        {
                            b1.Property<Guid>("CandidateProfileId")
                                .HasColumnType("uuid");

                            b1.PrimitiveCollection<string[]>("ArchitectureFocus")
                                .IsRequired()
                                .HasColumnType("text[]")
                                .HasColumnName("AiArchitectureFocus");

                            b1.PrimitiveCollection<string[]>("Certifications")
                                .IsRequired()
                                .HasColumnType("text[]")
                                .HasColumnName("AiCertifications");

                            b1.PrimitiveCollection<string[]>("CompanyTypes")
                                .IsRequired()
                                .HasColumnType("text[]")
                                .HasColumnName("AiCompanyTypes");

                            b1.PrimitiveCollection<string[]>("ContractPreferences")
                                .IsRequired()
                                .HasColumnType("text[]")
                                .HasColumnName("AiContractPreferences");

                            b1.PrimitiveCollection<string[]>("CoreSkills")
                                .IsRequired()
                                .HasColumnType("text[]")
                                .HasColumnName("AiCoreSkills");

                            b1.PrimitiveCollection<string[]>("DeliveryPractices")
                                .IsRequired()
                                .HasColumnType("text[]")
                                .HasColumnName("AiDeliveryPractices");

                            b1.PrimitiveCollection<string[]>("Domains")
                                .IsRequired()
                                .HasColumnType("text[]")
                                .HasColumnName("AiDomains");

                            b1.PrimitiveCollection<string[]>("EducationDetails")
                                .IsRequired()
                                .HasColumnType("text[]")
                                .HasColumnName("AiEducationDetails");

                            b1.PrimitiveCollection<string[]>("ExperienceHighlights")
                                .IsRequired()
                                .HasColumnType("text[]")
                                .HasColumnName("AiExperienceHighlights");

                            b1.Property<string>("ExperienceLevelYears")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)")
                                .HasColumnName("AiExperienceLevelYears");

                            b1.PrimitiveCollection<string[]>("Hobbies")
                                .IsRequired()
                                .HasColumnType("text[]")
                                .HasColumnName("AiHobbies");

                            b1.PrimitiveCollection<string[]>("Industries")
                                .IsRequired()
                                .HasColumnType("text[]")
                                .HasColumnName("AiIndustries");

                            b1.PrimitiveCollection<string[]>("LanguagesSpoken")
                                .IsRequired()
                                .HasColumnType("text[]")
                                .HasColumnName("AiLanguagesSpoken");

                            b1.PrimitiveCollection<string[]>("Locations")
                                .IsRequired()
                                .HasColumnType("text[]")
                                .HasColumnName("AiLocations");

                            b1.Property<string>("ManagementScope")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("AiManagementScope");

                            b1.PrimitiveCollection<string[]>("MobilityArea")
                                .IsRequired()
                                .HasColumnType("text[]")
                                .HasColumnName("AiMobilityArea");

                            b1.PrimitiveCollection<string[]>("MustHaveSkills")
                                .IsRequired()
                                .HasColumnType("text[]")
                                .HasColumnName("AiMustHaveSkills");

                            b1.PrimitiveCollection<string[]>("NiceToHaveSkills")
                                .IsRequired()
                                .HasColumnType("text[]")
                                .HasColumnName("AiNiceToHaveSkills");

                            b1.PrimitiveCollection<string[]>("PersonalityTraits")
                                .IsRequired()
                                .HasColumnType("text[]")
                                .HasColumnName("AiPersonalityTraits");

                            b1.PrimitiveCollection<string[]>("PreferredJobTitles")
                                .IsRequired()
                                .HasColumnType("text[]")
                                .HasColumnName("AiPreferredJobTitles");

                            b1.PrimitiveCollection<string[]>("SearchKeywords")
                                .IsRequired()
                                .HasColumnType("text[]")
                                .HasColumnName("AiSearchKeywords");

                            b1.PrimitiveCollection<string[]>("SecondarySkills")
                                .IsRequired()
                                .HasColumnType("text[]")
                                .HasColumnName("AiSecondarySkills");

                            b1.Property<string>("Seniority")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)")
                                .HasColumnName("AiSeniority");

                            b1.PrimitiveCollection<string[]>("SoftSkills")
                                .IsRequired()
                                .HasColumnType("text[]")
                                .HasColumnName("AiSoftSkills");

                            b1.Property<string>("Summary")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("AiSummary");

                            b1.PrimitiveCollection<string[]>("TargetRoles")
                                .IsRequired()
                                .HasColumnType("text[]")
                                .HasColumnName("AiTargetRoles");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("AiTitle");

                            b1.PrimitiveCollection<string[]>("WorkModes")
                                .IsRequired()
                                .HasColumnType("text[]")
                                .HasColumnName("AiWorkModes");

                            b1.HasKey("CandidateProfileId");

                            b1.ToTable("CandidateProfiles", "candidate_profile");

                            b1.WithOwner()
                                .HasForeignKey("CandidateProfileId");
                        });

                    b.Navigation("AiProfileInsight")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
