// <auto-generated />
using System;
using GrailJobApi.Modules.CandidateProfile.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GrailJobApi.Modules.CandidateProfile.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CandidateProfileDbContext))]
    partial class CandidateProfileDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("candidate_profile")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GrailJobApi.Modules.CandidateProfile.Domain.CandidateProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ExtractedText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ImportedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<long>("SizeInBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("CandidateProfiles", "candidate_profile");
                });

            modelBuilder.Entity("GrailJobApi.Modules.CandidateProfile.Domain.CandidateProfile", b =>
                {
                    b.OwnsOne("GrailJobApi.Modules.CandidateProfile.Domain.AiProfileInsight", "AiProfileInsight", b1 =>
                        {
                            b1.Property<Guid>("CandidateProfileId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Summary")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("AiSummary");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("AiTitle");

                            b1.HasKey("CandidateProfileId");

                            b1.ToTable("CandidateProfiles", "candidate_profile");

                            b1.WithOwner()
                                .HasForeignKey("CandidateProfileId");
                        });

                    b.Navigation("AiProfileInsight")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
