using CandidateProfileEntity = GrailJobApi.Modules.CandidateProfile.Domain.CandidateProfile;

namespace GrailJobApi.Modules.CandidateProfile.Presentation.Responses;

/// <summary>Candidate profile summary returned to the frontend.</summary>
public sealed record CvProfileResponse(
    bool HasCv,
    DateTime? UploadedAtUtc,
    string? Title,
    string? Summary,
    string? FileName,
    string[] TargetRoles,
    string[] PreferredJobTitles,
    string[] CoreSkills,
    string[] SecondarySkills,
    string[] MustHaveSkills,
    string[] NiceToHaveSkills,
    string[] Domains,
    string[] Industries,
    string[] CompanyTypes,
    string[] ExperienceHighlights,
    string[] ArchitectureFocus,
    string[] DeliveryPractices,
    string[] LanguagesSpoken,
    string[] WorkModes,
    string[] Locations,
    string[] MobilityArea,
    string? Seniority,
    string? ExperienceLevelYears,
    string? ManagementScope,
    string[] Certifications,
    string[] ContractPreferences,
    string[] SearchKeywords,
    string[] PersonalityTraits,
    string[] SoftSkills,
    string[] EducationDetails,
    string[] Hobbies)
{
    public static CvProfileResponse Empty() => new(
        false,
        null,
        null,
        null,
        null,
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        null,
        null,
        null,
        [],
        [],
        [],
        [],
        [],
        [],
        []);

    public static CvProfileResponse From(CandidateProfileEntity profile)
        => new(
            true,
            profile.ImportedAtUtc,
            EmptyToNull(profile.AiProfileInsight.Title),
            EmptyToNull(profile.AiProfileInsight.Summary),
            profile.OriginalFileName,
            profile.AiProfileInsight.TargetRoles,
            profile.AiProfileInsight.PreferredJobTitles,
            profile.AiProfileInsight.CoreSkills,
            profile.AiProfileInsight.SecondarySkills,
            profile.AiProfileInsight.MustHaveSkills,
            profile.AiProfileInsight.NiceToHaveSkills,
            profile.AiProfileInsight.Domains,
            profile.AiProfileInsight.Industries,
            profile.AiProfileInsight.CompanyTypes,
            profile.AiProfileInsight.ExperienceHighlights,
            profile.AiProfileInsight.ArchitectureFocus,
            profile.AiProfileInsight.DeliveryPractices,
            profile.AiProfileInsight.LanguagesSpoken,
            profile.AiProfileInsight.WorkModes,
            profile.AiProfileInsight.Locations,
            profile.AiProfileInsight.MobilityArea,
            EmptyToNull(profile.AiProfileInsight.Seniority),
            EmptyToNull(profile.AiProfileInsight.ExperienceLevelYears),
            EmptyToNull(profile.AiProfileInsight.ManagementScope),
            profile.AiProfileInsight.Certifications,
            profile.AiProfileInsight.ContractPreferences,
            profile.AiProfileInsight.SearchKeywords,
            profile.AiProfileInsight.PersonalityTraits,
            profile.AiProfileInsight.SoftSkills,
            profile.AiProfileInsight.EducationDetails,
            profile.AiProfileInsight.Hobbies);

    private static string? EmptyToNull(string value)
        => string.IsNullOrWhiteSpace(value) ? null : value;
}